name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Nix
        uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable

      - name: Enter Nix Shell and Build
        run: |
          nix-shell --run "cargo build --release"

      - name: Run tests
        run: |
          nix-shell --run "cargo test"
